### ISSUE TITLE
Power Washer and outdoor tools every cleaning/maintenance business should have

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#10]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
@SamHoffer hello, I'm interested in providing a blog post for this issue. Attached is the general outline of my approach to tackling the issue. Regards 
[General Article Outline_ Power Washer and outdoor tools every cleaning_maintenance business should have #10.docx](https://github.com/Taskbird/creator-community/files/8068260/General.Article.Outline_.Power.Washer.and.outdoor.tools.every.cleaning_maintenance.business.should.have.10.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya  Yeah, I'm liking this list, looks great! looking forward to the final piece
