### ISSUE TITLE
Home Exterior Cleaning Service

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#11]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
Hello @SamHoffer, I request your permission to handle this task/issue. Attached is the proposed general article outline. You can share with me if there is any content that can be added. Regards
[General Draft_ Home Exterior Cleaning Service #11.docx](https://github.com/Taskbird/creator-community/files/7862217/General.Draft_.Home.Exterior.Cleaning.Service.11.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya Hey, I like this outline! Do you think you'd be able to include information on how this may effectively reduce allergies for resident in the house. If not, not to worry but I think it could be a valuable piece of info!

**Comment by Mr254Kenya** [comment]
Hello, thanks for the reply. I believe I can search for the information
requested and add it to the content.
