### ISSUE TITLE
Laundry and linen service as part of your business offering 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#13]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
hello @SamHoffer, hope all is well with you. I'm interested in tackling this issue. Consequently, I have attached a document highlighting how I plan to tackle the blog post. Regards
[Laundry and linen service as part of your business offering.docx](https://github.com/Taskbird/creator-community/files/8168870/Laundry.and.linen.service.as.part.of.your.business.offering.docx)
