### ISSUE TITLE
Cleaning outdoor patios  

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#16]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by jfaria14** [comment]
Hi, I'd like to write an article for this topic

**Comment by SamHoffer** [comment]
Hey @jfaria14 thanks for reaching out! if you can please share your outline ideas for how you are going to tackle this topic that would be great. Additionally, if you are able to create a video for this topic instead of/ in conjunction with this article it would be preferred. Let me know if you have any questions, and welcome to the creators community!

**Comment by jfaria14** [comment]
@SamHoffer Sure I'll send the outline soon. This one I'll write but maybe the next one I can do a video thanks

**Comment by jfaria14** [comment]
[Outdoor Patio Cleaning_ Outline.docx](https://github.com/Taskbird/creator-community/files/7832062/Outdoor.Patio.Cleaning_.Outline.docx)

**Comment by SamHoffer** [comment]
@jfaria14, looks great! Go ahead and get started on your final draft. You can send your document to community@taskbird.com whenever you are finished.

**Comment by jfaria14** [comment]
Hi sam

Here is my finished article. let me know if I need to change anything.

Thank you, Joselyn

**Comment by jfaria14** [comment]
My apologies,

Here is the completed invoice for your review.

Thank you, Joselyn
