### ISSUE TITLE
Post lease cleaning 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#20]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic! 

When you submit your final draft email the file to Community@taskbird.com

**Comment by cassiclean** [comment]
I would like to tackle this topic

Outline
removal  of anything left by previous tenants (how to potentially earn extra here)
Full clean of each room 
entry way and patio areas
how to charge for this type of cleaning

**Comment by SamHoffer** [comment]
@cassiclean apologies for the late response. I like your outline, but do you think you could include how a cleaning business could find clients that are in need of post lease cleaning. Marketing, lead generation, where to look for clients of the sort? Let me know if you have questions.

**Comment by cassiclean** [comment]
article written and emailed

**Comment by SamHoffer** [comment]
@cassiclean Received! Thank you, I am reviewing it right now.
