### ISSUE TITLE
Car detailing

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#21]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic! 

When you submit your final draft send your file to community@taskbird.com

**Comment by cassiclean** [comment]
I’d like to create a video for this topic

**Comment by SamHoffer** [comment]
Sounds great @cassiclean, let me know if you need any feedback or help!

**Comment by cassiclean** [comment]
@SamHoffer  could you give me some guidelines for videos? such as how long it should be and any big dos or dont's for videos?

**Comment by SamHoffer** [comment]
@cassiclean we are looking for tutorial style videos and your best practices in this particular subject of cleaning. Try to keep the movement of the camera to a minimum as this can be hard to watch at times. This video will be used for Taskbird after the payment has been completed so we ask that you do not include advertising for your personal business. However, your bio will be visible to those who view our videos. Overall, we are open to seeing what you can come up with and if we need to edit anything we will communicate with you on what needs to be fixed.
