### ISSUE TITLE
Best carpet cleaning products and practices for commercial clients

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#3]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
Hello, @SamHoffer hope you and your team have had a great start to this year? I request to tackle this issue. I have attached the general outline for the task/article and of course, if you have anything you think I should add, please point it out and I will be more than happy to take a look at it. Regards
[General Draft_Best carpet cleaning products and practices for commercial clients #3.docx](https://github.com/Taskbird/creator-community/files/7862074/General.Draft_Best.carpet.cleaning.products.and.practices.for.commercial.clients.3.docx)

**Comment by SamHoffer** [comment]
Hey @Mr254Kenya, great start to the year and looking forward to all that will come! Hoping the same for you! I'm really liking this outline, great framework for some awesome detail. Looking forward to reading more about it! 

and again, thank you for you time.

**Comment by Mr254Kenya** [comment]
Thanks for replying and approving the outline. I will work on it.
