### ISSUE TITLE
Satisfaction Guarantee: a good business practice or recipe for disaster? 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#30]
How can a satisfaction guarantee attract business? Does is lead to more problems? How can this help a cleaning business? 

Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by cassiclean** [comment]
@SamHoffer  I will be submitting an outline for this topic
