### ISSUE TITLE
Why You Should Start a Cleaning Business, and What to Know Before You Get Started.

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#33]
Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

When you submit your final draft send your file to community@taskbird.com

**Comment by Mr254Kenya** [comment]
Hello, @SamHoffer I request your permission to handle this issue/topic. Attached is the proposed general outline for the blog post. Regards
[General Draft_ Things I wish I knew Before I Started a Cleaning Business #33.docx](https://github.com/Taskbird/creator-community/files/7862330/General.Draft_.Things.I.wish.I.knew.Before.I.Started.a.Cleaning.Business.33.docx)

**Comment by SamHoffer** [comment]
Hello @Mr254Kenya I do like the direction this article is going, however, I would like this piece to be covered from the perspective of an already established cleaning business owner. 

I am happy to change this topic to more closely fit your outline of " Why you should start a cleaning business, and what to know before you get started" 

If you are okay with this I will approve your outline for the revised blog topic. 

Thank you for your time and apologies for the delayed response.

**Comment by Mr254Kenya** [comment]
Hello, thanks for the reply, feels great to hear from you. If you can
approve the outline to match the revised topic that would be great.

**Comment by SamHoffer** [comment]
@Mr254Kenya you are good to go! Happy Writing!
