### ISSUE TITLE
Tips for cleaning during winter weather

### ISSUE THREAD

**Issue by cassiclean** [Taskbird/creator-community#34]
Over the years bad weather had create challenges for cleaners. Tips for dealing with these issues could be very useful to some

**Comment by cassiclean** [comment]
outline for this topic has been emailed @SamHoffer

**Comment by SamHoffer** [comment]
Outline is received and approved, I'll be eagerly awaiting this piece. Thank you @cassiclean

**Comment by cassiclean** [comment]
the article has been submitted via email.

**Comment by SamHoffer** [comment]
@cassiclean thank you, I will begin reviewing it ASAP
