### ISSUE TITLE
Best Natural Cleaning Products for Cleaning Companies: VIDEO & WRITTEN

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#46]
[Video Guidelines](https://github.com/Taskbird/creator-community/blob/main/Video%20Guidelines.pdf)

Email [Community@Taskbird.com](mailto:Community@Taskbird.com) you submissions and questions OR comment below

If you're new here read [How it works](https://github.com/Taskbird/creator-community/blob/main/How%20It%20Works.md) to take the right steps

**Comment by Mr254Kenya** [comment]
Hello, @SamHoffer hope you are doing well? I request your permission to handle this particular blog post task/issue. Attached is the general article outline. Regards


[Guideline_Best Natural Cleaning Products for Cleaning Companies- Written.docx](https://github.com/Taskbird/creator-community/files/8467131/Guideline_Best.Natural.Cleaning.Products.for.Cleaning.Companies-.Written.docx)
