### ISSUE TITLE
Professional window cleaning: Getting started

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#5]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by jfaria14** [comment]
Hi I can write an article about this topic and maybe create a video about it. Let me know

**Comment by SamHoffer** [comment]
@jfaria14 Hi, thank you for expressing your interest in this topic. Any video content that can be made for this topic would be preferred over the written piece. You are still welcome to write a topic, however. 

Please view our video guidelines in the "<> Code" tab in the top left of your page. Please reach out with any questions you have.
