### ISSUE TITLE
Removing Smoke Smell from a Property: VIDEO & WRTTEN

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#52]
[Video Guidelines](https://github.com/Taskbird/creator-community/blob/main/Video%20Guidelines.pdf)

Email [Community@Taskbird.com](mailto:Community@Taskbird.com) you submissions and questions OR comment below

If you're new here read [How it works](https://github.com/Taskbird/creator-community/blob/main/How%20It%20Works.md) to take the right steps

**Comment by Mr254Kenya** [comment]
@SamHoffer hello, I also register an interest to provide a blog post (written) for this issue. I have attached the general blog guideline, other suggestions are welcomed. Regards
[Blog Post Guideline_ Removing Smoke Smell from a Property #52.docx](https://github.com/Taskbird/creator-community/files/8253428/Blog.Post.Guideline_.Removing.Smoke.Smell.from.a.Property.52.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya Hey, I think this is a great outline, I've made some adjustments, however. Bellow is the outline you've sent me but it has been adjusted to be written for a cleaning company audience or someone who may be considering starting this service. 

1.Intro
2.Common areas that may house smoke residue include air ducts, carpets and rags, etc.
3.Tips for smoke smell removal
4.Equipment/products for removing smoke smell (Ozone machine?)
5.Why adding a smoke removal service will help your company gain clients 
6.Conclusion

**Comment by Mr254Kenya** [comment]
Thanks for the adjustment, looking forward to working on it. Regards
