### ISSUE TITLE
Mold Removal: What you need to know: VIDEO & WRITTEN

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#53]
[Video Guidelines](https://github.com/Taskbird/creator-community/blob/main/Video%20Guidelines.pdf)

Email [Community@Taskbird.com](mailto:Community@Taskbird.com) you submissions and questions OR comment below

If you're new here read [How it works](https://github.com/Taskbird/creator-community/blob/main/How%20It%20Works.md) to take the right steps

**Comment by Mr254Kenya** [comment]
@SamHoffer may be interested in tackling this issue. Just for your clarification, providing video and written work means the video has to be accompanied by a blog post of the usual number of words (above 1000)? Regards

**Comment by SamHoffer** [comment]
@Mr254Kenya What this entails is that we are in need of a video and a written blog for this topic. The written portion will follow the usual guidelines. As for the video portion the  [Video Guidelines](https://github.com/Taskbird/creator-community/blob/main/Video%20Guidelines.pdf) are outlined but we do encourage creative freedom. 

We do not require that both video and written are submitted at the same time or by the same community creators. To clarify, video and written are two separate pieces and one can be submitted without the other. 

If you do submit both video and written pieces for the same topic you will be compensated for both.

**Comment by Mr254Kenya** [comment]
Hello @SamHoffer it was nice to hear from you. Following your clarification, I register an interest to curate a blog post (written) for this particular issue. Consequently, I have supplied you with a general outline of how I plan to approach the issue. Any suggestions on the approach are humbly welcomed. Regard

[Draft Outline Mold Removal_ What you need to know-WRITTEN #53.docx](https://github.com/Taskbird/creator-community/files/8253303/Draft.Outline.Mold.Removal_.What.you.need.to.know-WRITTEN.53.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya Hey, you as well! Similar to the Topic #52 the outline for this great but the only adjustment that needs to be changed is the perspective/ audience. Here's the outline you sent me but with some adjustments. 

1.Introduction
2.Signs of mold attack in a house
3.Effects of mold on your health
4.How to prevent the growth of mold at a home
5.How to get rid of mold in a home
6.How professional mold removal services can benefit your business
7.Conclusion

**Comment by Mr254Kenya** [comment]
Okay, I understand. I will work with the adjustment
