### ISSUE TITLE
Commercial Cleaning: What your business needs to know

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#6]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by Mr254Kenya** [comment]
Hello, @SamHoffer, hope all is well? I request the opportunity to create a blog article on this topic. I have supplied you with the general article framework. If you can think of any other important part left out, please let me know. Regards
[General Article Guideline_ Commercial Cleaning_ What your business needs to know #6.docx](https://github.com/Taskbird/creator-community/files/7956655/General.Article.Guideline_.Commercial.Cleaning_.What.your.business.needs.to.know.6.docx)

**Comment by SamHoffer** [comment]
@Mr254Kenya I like your outline but I think the confusion here is in the topic provided. 
If I am wrong please correct me. However, I think it would be great to have this written for an audience that is looking to provide cleaning services to companies. Things to include might be the frame work of a cleaning company that specializes in commercial cleaning services, the price points, types of clientele, equipment and costs, team size, how to manage teams and projects, and the benefits that clients will gain from the service provided.

**Comment by Mr254Kenya** [comment]
@SamHoffer Hello, it is great to hear from you. Definitely, I agree that the topic given was maybe a bit confusing and not specific, that is why it may have pushed me to approach the task in a manner I had outlined. I now have a bit of an idea of what you meant. I can try and come up with a guideline to that effect or you try and refine the topic first before I come up with a potential guideline. Regards

**Comment by SamHoffer** [comment]
@Mr254Kenya This is exactly what I was hoping for for this article, thank you for making the adjustments! Whenever you have the final draft I'll be happy to go through it again.
