### ISSUE TITLE
Picking up after pets 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#7]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic!

**Comment by cassiclean** [comment]
I have tons of experience in dealing with cleaning up after pets from the pet-friendly STR I clean and the 2 dogs I clean up after in my own home. I can put together great information for this topic and would like to do so.

**Comment by SamHoffer** [comment]
@cassiclean I think this topic can only be written from those with first hand experience, so that is great. I do ask that you submit video content too. When you submit your ideas and information and we can go over some ideas for a video!

**Comment by cassiclean** [comment]
pet mess removal

steps keep pet hair to a minimal and complete removal from STR
essential tools for cleaning up after pets with product links
Dealing with pet urine and feces
I have tons of before and after pet mess photos

when I make videos does it have to show me doing the cleaning?
what other video ideas do you have?

**Comment by SamHoffer** [comment]
@cassiclean I really like these ideas and the photos will really strengthen this article too. For the video you can show as much as you self as you are comfortable with. A single arm POV angle of the pet cleaning could be good. Something that shows an arm (doesn't have to be you) cleaning lots of pet hair off surfaces, a fake or real pet mess being cleaned in steps. 

I was thinking if you want to just film these scenes I am more than happy to edit them into a congruent video.

**Comment by cassiclean** [comment]
okay, great, I will get to it. thanks!

**Comment by SamHoffer** [comment]
@cassiclean Looking forward to it! And as always reach out if you need anything
