### ISSUE TITLE
Creating a healthy working culture for your employees

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/creator-community#8]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by thaitee** [comment]
Hi, I'm interested in writing an article for this topic. Can I send my outline to an email address?

**Comment by SamHoffer** [comment]
@thaitee Thank you for reaching out about this topic, please submit your outline to this comment thread. After it has been approved you may submit your final piece to community@taskbird.com.
